### ISSUE TITLE
should use join/try_join to wait two task complete concurrency

### ISSUE THREAD

**Issue by pymongo** [KernelErr/foxear#1]
https://github.com/KernelErr/foxear/blob/0b2e396c513be31fec0eb68f9cebf17791b1f145/src/server.rs#L21

this line should use join or try_join to run future concurrency

**Comment by KernelErr** [comment]
Fixed in https://github.com/KernelErr/foxear/commit/1cb596d72c734b7f43bac3f2d6a8d50059f52d5c.
